export type ItemMasterField = {
  key: string;
  label: string;
  required: boolean;
};

export const itemMasterFields: ItemMasterField[] = [
  { key: 'warehouse', label: 'Warehouse', required: true },
  { key: 'company', label: 'COMPANY', required: true },
  { key: 'item_number', label: 'ITEM NUMBER', required: true },
  { key: 'item_group', label: 'ITEM GROUP', required: false },
  { key: 'item_main_group', label: 'ITEM MAIN GROUP', required: false },
  { key: 'item_sub_group', label: 'ITEM SUB- GROUP', required: false },
  { key: 'jis_prod_grp', label: 'JIS PROD-GRP', required: false },
  { key: 'vas_group', label: 'VAS GROUP', required: false },
  { key: 'check_group', label: 'CHECK GROUP', required: false },
  { key: 'matchcode', label: 'MATCHCODE', required: false },
  { key: 'item_grp_pick_time', label: 'ITEM GRP PICK TIME', required: false },
  { key: 'item_grp_ptwy_time', label: 'ITEM GRP PTWY TIME', required: false },
  { key: 'item_grp_stocktak_time', label: 'ITEM GRP STOCKTAK. TIME', required: false },
  { key: 'material_group', label: 'MATERIAL GROUP', required: false },
  { key: 'ean_no_gtin', label: 'EAN NO / GTIN', required: false },
  { key: 'ean_check', label: 'EAN CHECK', required: false },
  { key: 'display_item_images', label: 'DISPLAY ITEM IMAGES', required: false },
  { key: 'material_number', label: 'MATERIAL NUMBER', required: false },
  { key: 'material_thickness', label: 'MATERIAL THICKNESS', required: false },
  { key: 'material_width', label: 'MATERIAL WIDTH', required: false },
  { key: 'material_length', label: 'MATERIAL LENGTH', required: false },
  { key: 'item_description_1', label: 'ITEM DESCRIPTION 1', required: true },
  { key: 'item_description_2', label: 'ITEM DESCRIPTION 2', required: false },
  { key: 'item_description_3', label: 'ITEM DESCRIPTION 3', required: false },
  { key: 'item_short_description', label: 'ITEM SHORT DESCRIPTION', required: false },
  { key: 'sku_height', label: 'SKU HEIGHT', required: false },
  { key: 'key_qa_instruction', label: 'KEY QA INSTRUCTION', required: false },
  { key: 'quality_assurance_1_0', label: 'QUALITY ASSURANCE 1/0', required: false },
  { key: 'quality_code', label: 'QUALITY CODE', required: false },
  { key: 'add_goods_excluded', label: 'ADD GOODS EXCLUDED', required: false },
  { key: 'pick_strat', label: 'PICK STRAT.', required: false },
  { key: 'reserv_strat', label: 'RESERV. STRAT.', required: false },
  { key: 'reserv_threshold', label: 'RESERV. THRESHOLD', required: false },
  { key: 'reserv_span', label: 'RESERV.- SPAN', required: false },
  { key: 'customs_tariff_no', label: 'CUSTOMS TARIFF NO.', required: false },
  { key: 'last_inv_date', label: 'LAST INV. DATE', required: false },
  { key: 'stotak_cd', label: 'STOTAK CD', required: false },
  { key: 'standard_stor_loc', label: 'STANDARD STOR. LOC.', required: false },
  { key: 'standard_stor_area', label: 'STANDARD *STOR. AREA', required: false },
  { key: 'ptwy_compulsory', label: 'PTWY COMPULSORY', required: false },
  { key: 'whse_section', label: 'WHSE SECTION', required: false },
  { key: 'raw_item_length', label: 'RAW ITEM LENGTH', required: false },
  { key: 'raw_item_width', label: 'RAW ITEM WIDTH', required: false },
  { key: 'raw_item_heigth', label: 'RAW ITEM HEIGTH', required: false },
  { key: 'raw_item_area_gross', label: 'RAW ITEM AREA GROSS', required: false },
  { key: 'raw_item_area_net', label: 'RAW ITEM AREA NET', required: false },
  { key: 'raw_item_volume_gross', label: 'RAW ITEM VOLUME GROSS', required: false },
  { key: 'raw_item_volume_net', label: 'RAW ITEM VOLUME NET', required: false },
  { key: 'theoret_wgt_in_kg', label: 'THEORET.WGT IN KG', required: false },
  { key: 'net_wgt_in_kg', label: 'NET.WGT IN KG', required: false },
  { key: 'gross_wgt_in_kg', label: 'GROSS.WGT IN KG', required: false },
  { key: 'max_toleranz', label: 'MAX TOLERANZ', required: false },
  { key: 'volume_in_cm3', label: 'VOLUME IN CM3', required: false },
  { key: 'qty_per_cm3', label: 'QTY PER CM3', required: false },
  { key: 'unit_of_measure', label: 'UNIT OF MEASURE', required: false },
  { key: 'length_in_mm', label: 'LENGTH IN MM', required: false },
  { key: 'width_in_mm', label: 'WIDTH IN MM', required: false },
  { key: 'height_in_mm', label: 'HEIGHT IN MM', required: false },
  { key: 'pack_item_area_gross', label: 'PACK ITEM AREA GROSS', required: false },
  { key: 'pack_item_area_gross_2', label: 'PACK ITEM AREA GROSS', required: false },
  { key: 'pack_item_volume_gross', label: 'PACK ITEM VOLUME GROSS', required: false },
  { key: 'nesting_factor_length', label: 'NESTING FACTOR LENGTH', required: false },
  { key: 'nesting_factor_width', label: 'NESTING FACTOR WIDTH', required: false },
  { key: 'nesting_factor_height', label: 'NESTING FACTOR HEIGHT', required: false },
  { key: 'correction_factor_width', label: 'CORRECTION FACTOR WIDTH', required: false },
  { key: 'correction_factor_lenght', label: 'CORRECTION FACTOR LENGHT', required: false },
  { key: 'correction_factor_height', label: 'CORRECTION FACTOR HEIGHT', required: false },
  { key: 'piece_per_layer', label: 'PIECE PER LAYER', required: false },
  { key: 'theoret_wgt_pu_in_kg', label: 'THEORET. WGT PU IN KG', required: false },
  { key: 'net_wgt_pu_in_kg', label: 'NET. WGT PU IN KG', required: false },
  { key: 'gross_wgt_pu_in_kg', label: 'GROSS. WGT PU IN KG', required: false },
  { key: 'max_tolerance_pu', label: 'MAX TOLERANCE PU', required: false },
  { key: 'volume_pu_in_cm3', label: 'VOLUME PU IN CM3', required: false },
  { key: 'qty_per_cm3_2', label: 'QTY PER CM3', required: false },
  { key: 'content_qty', label: 'CONTENT QTY', required: false },
  { key: 'uom_of_pu', label: 'UOM OF PU', required: false },
  { key: 'pu_qty', label: 'PU QTY', required: false },
  { key: 'no_conversion_pu_1', label: 'NO CONVERSION PU 1', required: false },
  { key: 'length_pu_in_mm', label: 'LENGTH PU IN MM', required: false },
  { key: 'width_pu_in_mm', label: 'WIDTH PU IN MM', required: false },
  { key: 'height_pu_in_mm', label: 'HEIGHT PU IN MM', required: false },
  { key: 'nesting_factor_l_pu', label: 'NESTING FACTOR L PU', required: false },
  { key: 'nesting_factor_w_pu', label: 'NESTING FACTOR W PU', required: false },
  { key: 'nesting_factor_h_pu', label: 'NESTING FACTOR H PU', required: false },
  { key: 'correction_factor_w_pu', label: 'CORRECTION FACTOR W PU', required: false },
  { key: 'correction_factor_l_pu', label: 'CORRECTION FACTOR L PU', required: false },
  { key: 'correction_factor_h_pu', label: 'CORRECTION FACTOR H PU', required: false },
  { key: 'pu_per_layer', label: 'PU PER LAYER', required: false },
  { key: 'theoret_wgt_opu_in_kg', label: 'THEORET. WGT OPU IN KG', required: false },
  { key: 'net_wgt_opu_in_kg', label: 'NET. WGT OPU IN KG', required: false },
  { key: 'gross_wgt_opu_in_kg', label: 'GROSS. WGT OPU IN KG', required: false },
  { key: 'max_toleranz_opu', label: 'MAX TOLERANZ OPU', required: false },
  { key: 'volume_opu_in_cm3', label: 'VOLUME OPU IN CM3', required: false },
  { key: 'qty_per_cm3_3', label: 'QTY PER CM3', required: false },
  { key: 'uom_of_opu', label: 'UOM OF OPU', required: false },
  { key: 'outerpack_qty', label: 'OUTERPACK QTY', required: false },
  { key: 'no_convresion_pu_2', label: 'NO CONVRESION PU 2', required: false },
  { key: 'length_opu_in_mm', label: 'LENGTH OPU IN MM', required: false },
  { key: 'width_opu_in_mm', label: 'WIDTH OPU IN MM', required: false },
  { key: 'height_opu_in_mm', label: 'HEIGHT OPU IN MM', required: false },
  { key: 'nesting_factor_l_opu', label: 'NESTING FACTOR L OPU', required: false },
  { key: 'nesting_factor_w_opu', label: 'NESTING FACTOR W OPU', required: false },
  { key: 'nesting_factor_h_opu', label: 'NESTING FACTOR H OPU', required: false },
  { key: 'correction_factor_w_opu', label: 'CORRECTION FACTOR W OPU', required: false },
  { key: 'correction_factor_l_opu', label: 'CORRECTION FACTOR L OPU', required: false },
  { key: 'correction_factor_h_opu', label: 'CORRECTION FACTOR H OPU', required: false },
  { key: 'outer_package_per_layer', label: 'OUTER PACKAGE PER LAYER', required: false },
  { key: 'theoret_wgt_hu_in_kg', label: 'THEORET. WGT HU IN KG', required: false },
  { key: 'net_wgt_hu_in_kg', label: 'NET. WGT HU IN KG', required: false },
  { key: 'gross_wgt_hu_in_kg', label: 'GROSS. WGT HU IN KG', required: false },
  { key: 'max_tolerance_hu', label: 'MAX TOLERANCE HU', required: false },
  { key: 'volume_hu_in_cm3', label: 'VOLUME HU IN CM3', required: false },
  { key: 'qty_per_cm3_4', label: 'QTY PER CM3', required: false },
  { key: 'handling_unit', label: 'HANDLING UNIT', required: false },
  { key: 'qty_per_hu', label: 'QTY PER HU', required: false },
  { key: 'no_convresion_hu', label: 'NO CONVRESION HU', required: false },
  { key: 'length_hu_in_mm', label: 'LENGTH HU IN MM', required: false },
  { key: 'width_hu_in_mm', label: 'WIDTH HU IN MM', required: false },
  { key: 'height_hu_in_mm', label: 'HEIGHT HU IN MM', required: false },
  { key: 'nesting_factor_l_hu', label: 'NESTING FACTOR L HU', required: false },
  { key: 'nesting_factor_w_hu', label: 'NESTING FACTOR W HU', required: false },
  { key: 'nesting_factor_h_hu', label: 'NESTING FACTOR H HU', required: false },
  { key: 'correction_factor_w_hu', label: 'CORRECTION FACTOR W HU', required: false },
  { key: 'correction_factor_l_hu', label: 'CORRECTION FACTOR L HU', required: false },
  { key: 'correction_factor_h_hu', label: 'CORRECTION FACTOR H HU', required: false },
  { key: 'layers_per_pallet', label: 'LAYERS PER PALLET', required: false },
  { key: 'stack_height', label: 'STACK HEIGHT', required: false },
  { key: 'tolt_in_grad', label: 'TOLT IN GRAD', required: false },
  { key: 'unit_of_measure_host', label: 'UNIT OF MEASURE HOST', required: false },
  { key: 'unit_of_measure_iso_host', label: 'UNIT OF MEASURE ISO HOST', required: false },
  { key: 'rounding_control', label: 'ROUNDING: CONTROL', required: false },
  { key: 'rounding_singles', label: 'ROUNDING: SINGLES', required: false },
  { key: 'rounding_singles_2', label: 'ROUNDING: SINGLES', required: false },
  { key: 'rounding_outer_packs', label: 'ROUNDING: OUTER PACKS', required: false },
  { key: 'rounding_load_units', label: 'ROUNDING: LOAD.UNITS', required: false },
  { key: 'volume_factor', label: 'VOLUME FACTOR', required: false },
  { key: 'limit_pick_qty', label: 'LIMIT PICK QTY', required: false },
  { key: 'min_outp_qty', label: 'MIN OUTP.QTY', required: false },
  { key: 'scaling_item', label: 'SCALING ITEM', required: false },
  { key: 'rack', label: 'RACK', required: false },
  { key: 'shipunit_finish_good', label: 'SHIPUNIT FINISH.GOOD', required: false },
  { key: 'prod_prior_item', label: 'PROD. PRIOR. ITEM', required: false },
  { key: 'prod_orders_perm', label: 'PROD. ORDERS PERM.', required: false },
  { key: 'item_type', label: 'ITEM TYPE', required: false },
  { key: 'consi_mater', label: 'CONSI MATER.', required: false },
  { key: 'mat_owner', label: 'MAT.OWNER', required: false },
  { key: 'cold_material', label: 'COLD MATERIAL', required: false },
  { key: 'reserv_selection', label: 'RESERV SELECTION', required: false },
  { key: 'remaining_time_in_days', label: 'REMAINING TIME IN DAYS', required: false },
  { key: 'remain_time_in_gr_days', label: 'REMAIN.TIME IN GR [DAYS]', required: false },
  { key: 'max_bbd_in_days', label: 'MAX BBD IN [DAYS]', required: false },
  { key: 'quarantine_cd', label: 'QUARANTINE CD', required: false },
  { key: 'quarantine_time', label: 'QUARANTINE TIME', required: false },
  { key: 'new_qa_check_days', label: 'NEW QA CHECK DAYS', required: false },
  { key: 'maturity_date_in_days', label: 'MATURITY DATE IN DAYS', required: false },
  { key: 'single_price', label: 'SINGLE PRICE', required: false },
  { key: 'currency_key', label: 'CURRENCY KEY', required: false },
  { key: 'standard_price', label: 'STANDARD PRICE', required: false },
  { key: 'currency_key_2', label: 'CURRENCY KEY', required: false },
  { key: 'new_standard_price', label: 'NEW STANDARD PRICE', required: false },
  { key: 'currency_key_3', label: 'CURRENCY KEY', required: false },
  { key: 'cent_new_std', label: 'CENT.NEW STD +', required: false },
  { key: 'currency_key_4', label: 'CURRENCY KEY', required: false },
  { key: 'free_of_charge', label: 'FREE OF CHARGE', required: false },
  { key: 'rent_price', label: 'RENT PRICE', required: false },
  { key: 'currency_key_5', label: 'CURRENCY KEY', required: false },
  { key: 'new_rent_price', label: 'NEW RENT PRICE', required: false },
  { key: 'currency_key_6', label: 'CURRENCY KEY', required: false },
  { key: 'date_new_rent', label: 'DATE NEW RENT   +', required: false },
  { key: 'currency_key_7', label: 'CURRENCY KEY', required: false },
  { key: 'return_sku_no_compuls', label: 'RETURN. SKU-NO COMPULS.', required: false },
  { key: 'no_of_pce_list_lines', label: 'NO. OF PCE LIST LINES', required: false },
  { key: 'replacem_item_no', label: 'REPLACEM. ITEM NO.', required: false },
  { key: 'item_reference', label: 'ITEM REFERENCE', required: false },
  { key: 'item_returnable_1', label: 'ITEM RETURNABLE 1', required: false },
  { key: 'item_returnable_2', label: 'ITEM RETURNABLE 2', required: false },
  { key: 'item_returnable_3', label: 'ITEM RETURNABLE 3', required: false },
  { key: 'item_returnable_type', label: 'ITEM RETURNABLE TYPE', required: false },
  { key: 'returnable_item_seq', label: 'RETURNABLE- ITEM-SEQ.', required: false },
  { key: 'total_invent', label: 'TOTAL INVENT.', required: false },
  { key: 'blocked_qty', label: 'BLOCKED QTY', required: false },
  { key: 'avail_qty', label: 'AVAIL. QTY', required: false },
  { key: 'item_lot_compuls', label: 'ITEM LOT COMPULS.', required: false },
  { key: 'item_bbd_compuls', label: 'ITEM BBD COMPULS.', required: false },
  { key: 'item_variety_compuls', label: 'ITEM VARIETY COMPULS.', required: false },
  { key: 'item_labelling', label: 'ITEM LABELLING', required: false },
  { key: 'scal_compul_with_pick', label: 'SCAL.COMPUL WITH PICK', required: false },
  { key: 'single_item_picking', label: 'SINGLE ITEM PICKING', required: false },
  { key: 'item_group_picking', label: 'ITEM GROUP PICKING', required: false },
  { key: 's_n_compu_with_pick', label: 'S/N.COMPU. WITH PICK', required: false },
  { key: 's_n_compu_receiving', label: 'S/N.COMPU RECEIVING', required: false },
  { key: 'ser_no_inventory_pickup', label: 'SER.NO. INVENTORY PICKUP', required: false },
  { key: 'ser_no_inv_booking', label: 'SER.NO. INV. BOOKING', required: false },
  { key: 'ser_no_without_ref', label: 'SER.NO. WITHOUT REF.', required: false },
  { key: 'serial_no_time_of_capt', label: 'SERIAL NO TIME OF CAPT.', required: false },
  { key: 'recovery_period', label: 'RECOVERY PERIOD', required: false },
  { key: 'goods_group', label: 'GOODS GROUP', required: false },
  { key: 'rem_qty_display_in', label: 'REM.QTY- DISPLAY IN %', required: false },
  { key: 'rem_qty_display_in_qu', label: 'REM.QTY- DISPLAY IN QU', required: false },
  { key: 'rem_goods_value_display', label: 'REM.GOODS VALUE DISPLAY', required: false },
  { key: 'days_in_workcalender', label: 'DAYS IN WORKCALENDER', required: false },
  { key: 'no_of_boxes', label: 'NO OF BOXES', required: false },
  { key: 'manufacturer', label: 'MANUFACTURER', required: false },
  { key: 'supplier_no', label: 'SUPPLIER NO', required: false },
  { key: 'works_no', label: 'WORKS NO', required: false },
  { key: 'item_comment_1', label: 'ITEM COMMENT 1', required: false },
  { key: 'item_comment_2', label: 'ITEM COMMENT 2', required: false },
  { key: 'item_comment_3', label: 'ITEM COMMENT 3', required: false },
  { key: 'equipping_remark_1', label: 'EQUIPPING REMARK 1', required: false },
  { key: 'equipping_remark_2', label: 'EQUIPPING REMARK 2', required: false },
  { key: 'equipping_remark_3', label: 'EQUIPPING REMARK 3', required: false },
  { key: 'new_record_host', label: 'NEW RECORD HOST', required: false },
  { key: 'not_host_relevant', label: 'NOT HOST RELEVANT', required: false },
  { key: 'dropped_goods_code', label: 'DROPPED GOODS CODE', required: false },
  { key: 'hazagoods_indicator', label: 'HAZAGOODS INDICATOR', required: false },
  { key: 'print_ucc_label', label: 'PRINT UCC LABEL', required: false },
  { key: 'shipmethod_excluded', label: 'SHIPMETHOD EXCLUDED', required: false },
  { key: 'pack_loc_relevant', label: 'PACK LOC. RELEVANT', required: false },
  { key: 'trading_unit', label: 'TRADING- UNIT', required: false },
  { key: 'date_last_entry', label: 'DATE LAST ENTRY', required: false },
  { key: 'date_last_exit', label: 'DATE LAST EXIT', required: false },
  { key: 'delete_cd', label: 'DELETE CD', required: false },
  { key: 'delete_record_date', label: 'DELETE RECORD DATE', required: false },
  { key: 'inactive_cd', label: 'INACTIVE CD', required: false },
  { key: 'rec_inactive_date', label: 'REC INACTIVE DATE', required: false },
  { key: 'sap_idoc_number', label: 'SAP IDOC NUMBER', required: false },
  { key: 'user_last_modification', label: 'USER LAST MODIFICATION', required: false },
  { key: 'terminal_last_modi', label: 'TERMINAL LAST MODI.', required: false },
  { key: 'modifik_date', label: 'MODIFIK. DATE', required: false },
  { key: 'modifik_time', label: 'MODIFIK. TIME', required: false },
  { key: 'upd_host_required', label: 'UPD. HOST REQUIRED', required: false },
  { key: 'last_upd_to_host_date', label: 'LAST UPD. TO HOST - DATE', required: false },
  { key: 'last_upd_to_host_time', label: 'LAST UPD. TO HOST - TIME', required: false },
  { key: 'coc_mixed_storage', label: 'COC MIXED STORAGE', required: false },
  { key: 'merchandise_group', label: 'MERCHANDISE GROUP', required: false },
  { key: 'merchandise_group_2', label: 'MERCHANDISE GROUP 2', required: false },
  { key: 'merchandise_group_3', label: 'MERCHANDISE GROUP 3', required: false },
  { key: 'range_of_use', label: 'RANGE OF USE', required: false },
  { key: 'minimum_quantity', label: 'MINIMUM QUANTITY', required: false },
  { key: 'reason_quantity_change', label: 'REASON QUANTITY CHANGE', required: false },
  { key: 'variant_segment', label: 'VARIANT SEGMENT', required: false },
  { key: 'variant_name', label: 'VARIANT NAME', required: false },
  { key: 'variant_usage_1', label: 'VARIANT USAGE 1', required: false },
  { key: 'variant_usage_2', label: 'VARIANT USAGE 2', required: false },
  { key: 'variant_usage_3', label: 'VARIANT USAGE 3', required: false },
  { key: 'variant_usage_4', label: 'VARIANT USAGE 4', required: false },
  { key: 'variant_usage_5', label: 'VARIANT USAGE 5', required: false },
  { key: 'matrix_info', label: 'MATRIX INFO', required: false },
  { key: 'matrix_x_axis_1', label: 'MATRIX X-AXIS 1', required: false },
  { key: 'matrix_y_axis_1', label: 'MATRIX Y-AXIS 1', required: false },
  { key: 'matrix_y_axis_2', label: 'MATRIX Y-AXIS 2', required: false },
  { key: 'variant_template', label: 'VARIANT TEMPLATE', required: false },
  { key: 'brand_name', label: 'BRAND- NAME', required: false },
  { key: 'shipping_hu_type', label: 'SHIPPING HU TYPE', required: false },
  { key: 'splitt_kz_versand_lm', label: 'SPLITT-KZ VERSAND-LM', required: false },
  { key: 'residue_stor_loc', label: 'RESIDUE STOR.LOC', required: false },
  { key: 'residue_stor_area', label: 'RESIDUE STOR.AREA', required: false },
  { key: 'country_of_origin', label: 'COUNTRY OF ORIGIN', required: false },
  { key: 'not_reserv_part_quant', label: 'NOT RESERV. PART QUANT.', required: false },
  { key: 'measure_date', label: 'MEASURE- DATE', required: false },
  { key: 'measure_time', label: 'MEASURE- TIME', required: false },
  { key: 'measure_user', label: 'MEASURE- USER', required: false },
  { key: 'measure_terminal', label: 'MEASURE TERMINAL', required: false },
  { key: 'vas_profile_1', label: 'VAS PROFILE 1', required: false },
  { key: 'vas_profile_2', label: 'VAS PROFILE 2', required: false },
  { key: 'vas_profile_3', label: 'VAS PROFILE 3', required: false },
  { key: 'vas_profile_4', label: 'VAS PROFILE 4', required: false },
  { key: 'vas_profile_5', label: 'VAS PROFILE 5', required: false },
  { key: 'vas_profile_6', label: 'VAS PROFILE 6', required: false },
  { key: 'vas_profile_7', label: 'VAS PROFILE 7', required: false },
  { key: 'vas_profile_8', label: 'VAS PROFILE 8', required: false },
  { key: 'vas_profile_9', label: 'VAS PROFILE 9', required: false },
  { key: 'check_pos_pattern', label: 'CHECK POS- PATTERN', required: false },
  { key: 'check_neg_pattern', label: 'CHECK NEG- PATTERN', required: false },
  { key: 'combi_label', label: 'COMBI LABEL', required: false },
  { key: 's_n_barcode_type', label: 'S/N BARCODE TYPE', required: false },
  { key: 'sepa_ator_qr', label: 'SEPA- ATOR QR', required: false },
  { key: 'forbid_lfs_numbers', label: 'FORBID LFS-NUMBERS', required: false },
  { key: 'forbid_ean', label: 'FORBID EAN', required: false },
  { key: 'duration_produc_sec', label: 'DURATION PRODUC. [SEC]', required: false },
  { key: 'duration_prepare_sek', label: 'DURATION PREPARE [SEK]', required: false },
  { key: 'eff_dur_produc_sec', label: 'EFF. DUR. PRODUC. [SEC]', required: false },
  { key: 'additional_package', label: 'ADDITIONAL PACKAGE', required: false },
  { key: 'distribute_record', label: 'DISTRIBUTE RECORD', required: false },
];

export const itemMasterUniqueKeys = ["warehouse", "company", "item_number"] as const;
export const itemMasterListKeys = ["warehouse", "company", "item_number", "item_description_1"] as const;
