import type { Item } from "@/lib/mock-data";
import { itemMasterFields } from "@/lib/item-master-fields";
import { items as fallbackItems } from "@/lib/mock-data";
import { createSupabaseServerClient } from "@/lib/supabase/server";
function getAuditUser() { return process.env.APP_DEFAULT_USER?.trim() || "Akshay"; }
function mapItemRecord(row: Record<string, unknown>): Item { const mapped: Record<string, string> = {}; for (const field of itemMasterFields) { mapped[field.key] = String(row[field.key] ?? ""); } return mapped as Item; }
function filterItems(items: Item[], query?: string) { if (!query) return items; const normalized = query.trim().toLowerCase(); return items.filter((item) => itemMasterFields.some((field) => String(item[field.key] ?? "").toLowerCase().includes(normalized))); }
export async function getItems(query?: string): Promise<{ items: Item[]; source: "supabase" | "mock"; error?: string }> { const supabase = createSupabaseServerClient(); if (!supabase) { return { items: filterItems(fallbackItems, query), source: "mock", error: "Missing Supabase environment variables." }; } const { data, error } = await (supabase.from("items") as any).select("*").order("warehouse", { ascending: true }).order("company", { ascending: true }).order("item_number", { ascending: true }); if (error || !data) { return { items: filterItems(fallbackItems, query), source: "mock", error: error?.message ?? "Unable to load items from Supabase." }; } return { items: filterItems((data as Record<string, unknown>[]).map(mapItemRecord), query), source: "supabase" }; }
export async function createItem(input: Record<string, string>) { const supabase = createSupabaseServerClient(); if (!supabase) return { ok: false as const, message: "Supabase environment variables are missing." }; const payload: Record<string, string> = {}; for (const field of itemMasterFields) { payload[field.key] = input[field.key] ?? ""; } payload.created_by_user = getAuditUser(); payload.updated_by_user = getAuditUser(); const { error } = await (supabase.from("items") as any).insert(payload); if (error) return { ok: false as const, message: error.message }; return { ok: true as const }; }
export async function updateItem(identity: { warehouse: string; company: string; item_number: string }, input: Record<string, string>) { const supabase = createSupabaseServerClient(); if (!supabase) return { ok: false as const, message: "Supabase environment variables are missing." }; const payload: Record<string, string> = {}; for (const field of itemMasterFields) { payload[field.key] = input[field.key] ?? ""; } payload.updated_by_user = getAuditUser(); const { error } = await (supabase.from("items") as any).update(payload).eq("warehouse", identity.warehouse).eq("company", identity.company).eq("item_number", identity.item_number); if (error) return { ok: false as const, message: error.message }; return { ok: true as const }; }
export async function deleteItem(identity: { warehouse: string; company: string; item_number: string }) { const supabase = createSupabaseServerClient(); if (!supabase) return { ok: false as const, message: "Supabase environment variables are missing." }; const { error } = await (supabase.from("items") as any).delete().eq("warehouse", identity.warehouse).eq("company", identity.company).eq("item_number", identity.item_number); if (error) return { ok: false as const, message: error.message }; return { ok: true as const }; }
